//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogMeasurement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"E:\\Alle Brugere\\Klaus\\Programmering" +
            "\\Visual Studio\\C#\\PhysicalMeasure\\LogMeasurement\\Database\\Measurements.mdf\";Inte" +
            "grated Security=True;Connect Timeout=30")]
        public string MeasurementsConnectionString {
            get {
                return ((string)(this["MeasurementsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SORTE-PC\\KBLSQL;Initial Catalog=MEASUREMENTS;Integrated Security=True" +
            "")]
        public string MEASUREMENTSConnectionStringNew {
            get {
                return ((string)(this["MEASUREMENTSConnectionStringNew"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v12.0;AttachDbFilename=\"E:\\Alle Brugere\\Klaus\\Programmering" +
            "\\Visual Studio\\C#\\PhysicalMeasure\\LogMeasurement\\Database\\Measurements.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string MeasurementsConnectionString2
        {
            get
            {
                return ((string)(this["MeasurementsConnectionString2"]));
            }
        }

    }
}
