/*****************************************************************************************************
* This code was generated by a tool.                                                                 *
* Generated 2016-12-12 02:37:27 from AssemblyInfo.tt                                                 *
*                                                                                                    *
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.     *
*****************************************************************************************************/

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("KBL.Extensions")]
[assembly: AssemblyDescription("C# class extension methodes for Byte, SByte, Byte[], SByte[], Double, String, DateTime, StringBuilder, IEnumerable, T[], Assembly")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
// [assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Kilo Bravo")]
[assembly: AssemblyProduct("KBL.Extensions")]
[assembly: AssemblyCopyright("Copyright © 2015-2016 Kilo Bravo")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]


// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("7139b888-5ce1-4604-b2e8-19fd45bc8b0e")]

//  Build at  2016-12-12 02:37:27 2016-12-12 02:30:00
//  major:    1
//  minor:    0
//  build:    6190
//  revision: 4500

[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyFileVersion("1.0.6190.4500")]
[assembly: AssemblyInformationalVersion("1.0.6190.4500")]

