/*****************************************************************************************************
* This code was generated by a tool.                                                                 *
* Generated 2019-06-21 20:24:59 from AssemblyInfo.tt                                                 *
*                                                                                                    *
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.     *
*****************************************************************************************************/

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("PhysicalMeasure")]
[assembly: AssemblyDescription("Physical Unit System Framework. PhysicalMeasure is a C# library for handling physical quantities by specifying value and unit. Scaling of units and conversions between multiple unit systems are supported.")]

#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
// [assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Kilo Bravo")]
[assembly: AssemblyProduct("PhysicalMeasure")]
// [assembly: AssemblyCopyright("Copyright © 2010-2019 Kilo Bravo")]
[assembly: AssemblyCopyright("Copyright © 2010-2025 Kilo Bravo")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

[assembly: CLSCompliant(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("c12e9e3a-4f77-4b3b-9175-5f30dbb00be9")]

//  Build at  2019-06-21 20:24:59 2019-06-21 20:20:00
//  major:    3
//  minor:    0
//  build:    7111
//  revision: 36600

/**
[assembly: AssemblyVersion("4.0.7151.15496")]
[assembly: AssemblyFileVersion("4.0.7151.15496")]
[assembly: AssemblyInformationalVersion("4.0.7155")]
**/

[assembly: AssemblyVersion("4.0.*")]

[assembly: InternalsVisibleTo("PhysCalculatorTests")]
