/*****************************************************************************************************
* This code was generated by a tool.                                                                 *
* Generated 2016-06-19 15:27:45 from AssemblyInfo.tt                                                 *
*                                                                                                    *
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.     *
*****************************************************************************************************/

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("PhysCalc")]
[assembly: AssemblyDescription("Physical quantity calculator using PhysicalMeasure")]
 
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
// [assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Kilo Bravo")]
[assembly: AssemblyProduct("PhysicalMeasure")]
[assembly: AssemblyCopyright("Copyright © 2010-2016 Kilo Bravo")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("9e19d828-26ef-460d-8d72-a0f3c9b675f4")]

//  Build at  2016-06-19 15:27:45 2016-06-19 15:20:00
//  major:    3
//  minor:    0
//  build:    6014
//  revision: 27600

[assembly: AssemblyVersion("3.0")]
[assembly: AssemblyFileVersion("3.0.6014.27600")]
[assembly: AssemblyInformationalVersion("3.0.6014.27600")]


[assembly: InternalsVisibleTo("PhysCalculatorTests")]
