/*****************************************************************************************************
* This code was generated by a tool.                                                                 *
// Auto generation disabled  * Generated 2019-06-21 20:24:59 from AssemblyInfo.tt                                                 *
*                                                                                                    *
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.     *
*****************************************************************************************************/

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("PhysCalc")]
[assembly: AssemblyDescription("Physical quantity calculator using PhysicalMeasure")]
 
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
// [assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("Kilo Bravo")]
[assembly: AssemblyProduct("PhysicalMeasure")]
// [assembly: AssemblyCopyright("Copyright © 2010-2019 Kilo Bravo")]
[assembly: AssemblyCopyright("Copyright © 2010-2025 Kilo Bravo")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("9e19d828-26ef-460d-8d72-a0f3c9b675f4")]

//  Build at  2019-06-21 20:24:59 2019-06-21 20:20:00
//  major:    3
//  minor:    0
//  build:    7111
//  revision: 36600

// [assembly: AssemblyVersion("3.0.*")]
[assembly: AssemblyVersion("4.0.*")]
// [assembly: AssemblyFileVersion("3.0.7151.15496")]
// [assembly: AssemblyInformationalVersion("3.0.7116")]

// [assembly: AssemblyFileVersion("3.0.9403.23400")]
// [assembly: AssemblyInformationalVersion("3.0.9411")]

// [assembly: AssemblyFileVersion("3.0.9403.23400")]
// [assembly: AssemblyInformationalVersion("3.0.9411")]


[assembly: InternalsVisibleTo("PhysCalculatorTests")]

